name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install -qq gcc-10 g++-10
      - name: build
        run: |
          cd examples
          export CC=gcc-10
          export CXX=g++-10
          CC=gcc-10 CXX=g++-10 make
        env:
          CC: gcc-10
          CXX: g++-10
          
  build-linux-clang:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt-get update
          sudo apt-get install -qq clang++
      - name: build
        run: |
          cd examples
          make
        env:
          CC: clang
          CXX: clang++
          
  build-macos-clang:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          brew install gcc@10
      - name: build
        run: |
          cd examples
          make
        env:
          CC: clang
          CXX: clang++
          
